title: Félix RL
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a physicist building my career mostly around Data Science, Big Data and Cybersecurity.<br>
  With a passion for learning and interested in being part of innovative and ambitious projects, continue to push forward on my capabilities to be better. 
  <br><br>
  Enthusiastic with great communicative skills, analyst, decisive, good team worker and technology lover.<br>
  Outside work I enjoy sports activities and try to do some research during free time, if Netflix is not available. 
  <br><br>
  <a href="https://www.linkedin.com/in/felagonell/">Find me on LinkedIn</a><br>
  <a href="https://github.com/feliux?tab=repositories">Take a look to my personal projects</a><br>
theme: jekyll-theme-hacker
google_analytics: G-8X83Y4W0KX
