title: Félix RL
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Software Engineer specialized in cybersecurity, big data and machine learning. Polymaths who loves Vim and enjoys customizing his development environment.<br>
  Interested in devising a better problem-solving method for challenging projects... And always learning new technologies and tools if the need arises.
  <br><br>
  <a href="https://www.linkedin.com/in/felagonell/">Find me on LinkedIn</a><br>
  <a href="https://github.com/feliux?tab=repositories">Take a look to my personal projects</a><br>
theme: jekyll-theme-hacker
google_analytics: G-8X83Y4W0KX
